[project]
name = "opencv-chess-fen"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.5.2",
]
